### ISSUE TITLE
kurtosis: command not found

### ISSUE THREAD

**Issue by Mouradif** [kurtosis-tech/near-kurtosis-module#37]
When trying to run the `launch-local-near-cluster.sh` script, I get the error `kurtosis: command not found`.

In the demo I watched on the video, the script pulled a docker container, yet I can't seem to find any docker command in the script. Am I using a new (broken) version?

**Comment by Mouradif** [comment]
Someone in NEAR's Discord gave me the solution. I installed `kurtosis-cli`.

I think the info should be in the README at the prerequisites part. Along with "Install Docker" and "Install `near-cli`" somewhere it should be mentionned that `kurtosis-cli` should be installed

**Comment by mieubrisse** [comment]
Hey @Mouradif , this is actually step #3 on the "Install Prerequisites"! sounds like it's buried too far down though, so I'll make it the first step

**Comment by Mouradif** [comment]
I can't believe I missed it 😵‍💫 trying to learn new tech while sleep deprived is never a good idea
