### ISSUE TITLE
Configurable root account

### ISSUE THREAD

**Issue by dakom** [kurtosis-tech/near-kurtosis-module#52]
Similar in spirit to https://github.com/kurtosis-tech/near-kurtosis-module/issues/41, having a configurable root account would make reproducible environments much simpler

As it is right now, launching the enclave logs a private/public keypair for test.near, but this changes everytime

Instead, it would be great to take a `seed-phrase` or `private-key` parameter, and then only fallback to the current random generation if none is provided. In terms of seed phrase vs private key, I think seed phrase would be more ideal since can then also be used with GUI wallets

**Comment by mieubrisse** [comment]
Closing in favor of #57 , now that we have a static validator key each time
