### ISSUE TITLE
Local wallet lookup based on seed phrase.

### ISSUE THREAD

**Issue by dmitryr117** [kurtosis-tech/near-kurtosis-module#78]
I tried to experiment with seed phrase based wallet recovery on local wallet. Cleared application site data and tried to re-import wallet using seed phrase. It keeps giving error:
**No accounts were found for this passphrase.**
The seed phrase derived public key was correct though.

When I checked Network tab in Chrome dev tools - it seems to be sending request to acquire wallet data to:
https://testnet-api.kitwallet.app/publicKey/ed25519:5djZqejwDmPK5oHDyGadCceiUsYH2ugJXWUoP48fAAuX/accounts

I think it is an actual testnet address which has no clue about my local keys.

**Comment by mieubrisse** [comment]
Hey @dmitryr117 thanks for reporting. The NEAR dev team recently switched to using a shared DynamoDB instance, which unfortunately isn't accessible outside the NEAR org. We've seen this cause issues with the account creation/recovery process and have filed a ticket with the team, though it's still open: https://github.com/near/near-contract-helper/issues/621 I'll give a ping over there as well

**Comment by mieubrisse** [comment]
Hey @dmitryr117 , wanted to circle back that this is finally fixed on the NEAR side, and things should be working again inside the module!
